/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pdfcombine;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfCopy;
import com.itextpdf.text.pdf.PdfReader;
import com.itextpdf.text.pdf.PdfSmartCopy;
import java.awt.AWTException;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Attar
 */
public class PDFCombine extends javax.swing.JFrame {

    DefaultListModel<String> l1;

    /**
     * Creates new form PDFCombine1
     */
    public PDFCombine() {
        initComponents();
        l1 = new DefaultListModel<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        addFilePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addFolderPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        removeFilePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        settingPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        exitPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        bCombine = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        lOutputPath = new javax.swing.JLabel();
        bUp = new javax.swing.JButton();
        bDown = new javax.swing.JButton();
        bDown1 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PDF Combine");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setName("PDFCombine"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        addFilePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addFilePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addFilePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addFilePanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addFilePanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addFilePanelMouseReleased(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/add.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setText("ADD FILE(S)");

        javax.swing.GroupLayout addFilePanelLayout = new javax.swing.GroupLayout(addFilePanel);
        addFilePanel.setLayout(addFilePanelLayout);
        addFilePanelLayout.setHorizontalGroup(
            addFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFilePanelLayout.createSequentialGroup()
                .addGap(0, 33, Short.MAX_VALUE)
                .addGroup(addFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21))
        );
        addFilePanelLayout.setVerticalGroup(
            addFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFilePanelLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        addFolderPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addFolderPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addFolderPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addFolderPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addFolderPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addFolderPanelMouseReleased(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/folder.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setText("ADD FOLDER");

        javax.swing.GroupLayout addFolderPanelLayout = new javax.swing.GroupLayout(addFolderPanel);
        addFolderPanel.setLayout(addFolderPanelLayout);
        addFolderPanelLayout.setHorizontalGroup(
            addFolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFolderPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(addFolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        addFolderPanelLayout.setVerticalGroup(
            addFolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFolderPanelLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );

        removeFilePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeFilePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removeFilePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removeFilePanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeFilePanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                removeFilePanelMouseReleased(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/delete.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel7.setText("REMOVE");

        javax.swing.GroupLayout removeFilePanelLayout = new javax.swing.GroupLayout(removeFilePanel);
        removeFilePanel.setLayout(removeFilePanelLayout);
        removeFilePanelLayout.setHorizontalGroup(
            removeFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeFilePanelLayout.createSequentialGroup()
                .addGroup(removeFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removeFilePanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel7))
                    .addGroup(removeFilePanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6)))
                .addContainerGap())
        );
        removeFilePanelLayout.setVerticalGroup(
            removeFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeFilePanelLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );

        settingPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                settingPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                settingPanelMouseReleased(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/about.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel9.setText("ABOUT");

        javax.swing.GroupLayout settingPanelLayout = new javax.swing.GroupLayout(settingPanel);
        settingPanel.setLayout(settingPanelLayout);
        settingPanelLayout.setHorizontalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPanelLayout.createSequentialGroup()
                .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settingPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(settingPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel9)))
                .addContainerGap())
        );
        settingPanelLayout.setVerticalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPanelLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel9))
        );

        exitPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitPanelMouseReleased(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/exit.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel11.setText("EXIT");

        javax.swing.GroupLayout exitPanelLayout = new javax.swing.GroupLayout(exitPanel);
        exitPanel.setLayout(exitPanelLayout);
        exitPanelLayout.setHorizontalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitPanelLayout.createSequentialGroup()
                .addGroup(exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(exitPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(exitPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel11)))
                .addContainerGap())
        );
        exitPanelLayout.setVerticalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitPanelLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel11))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addFilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(addFolderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(removeFilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(settingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addFilePanel, addFolderPanel, exitPanel, removeFilePanel, settingPanel});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addFolderPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeFilePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(settingPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addFilePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addFolderPanel, exitPanel, removeFilePanel, settingPanel});

        itemList.setNextFocusableComponent(bCombine);
        jScrollPane1.setViewportView(itemList);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("ITEM LIST");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("PROGRESS");

        bCombine.setText("COMBINE");
        bCombine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCombineActionPerformed(evt);
            }
        });

        jLabel13.setText("Output Path:");

        lOutputPath.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lOutputPathMouseClicked(evt);
            }
        });

        bUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/up-arrow.png"))); // NOI18N
        bUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUpActionPerformed(evt);
            }
        });

        bDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/down-arrow.png"))); // NOI18N
        bDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDownActionPerformed(evt);
            }
        });

        bDown1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/reverse.png"))); // NOI18N
        bDown1.setToolTipText("Revese Order of List");
        bDown1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDown1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bCombine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bDown1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lOutputPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bUp, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bDown, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bDown1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bCombine, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lOutputPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void addFilePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addFilePanelMouseEntered
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/add-hover.png")));
    }//GEN-LAST:event_addFilePanelMouseEntered

    private void addFilePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addFilePanelMouseExited
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/add.png")));
    }//GEN-LAST:event_addFilePanelMouseExited

    private void addFolderPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addFolderPanelMouseEntered
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/folder-hover.png")));
    }//GEN-LAST:event_addFolderPanelMouseEntered

    private void addFolderPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addFolderPanelMouseExited
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/folder.png")));
    }//GEN-LAST:event_addFolderPanelMouseExited

    private void addFilePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addFilePanelMouseClicked
        progressBar.setValue(0);

        final JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Choose one or more Files");
        fc.setMultiSelectionEnabled(true);
        int returnVal = fc.showOpenDialog(this);
        File file[];
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            file = fc.getSelectedFiles();

            addFilePathtoList(file, "file");
        }
    }//GEN-LAST:event_addFilePanelMouseClicked

    private void addFolderPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addFolderPanelMouseClicked
        progressBar.setValue(0);

        final JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Select Folder");
        fc.setMultiSelectionEnabled(false);
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = fc.showOpenDialog(this);
        File file[];
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File folder = fc.getSelectedFile();
            file = folder.listFiles();
            addFilePathtoList(file, "folder");
        }
    }//GEN-LAST:event_addFolderPanelMouseClicked

    private void removeFilePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeFilePanelMouseClicked
        int[] indexSelectedFile = itemList.getSelectedIndices();
        for (int i = indexSelectedFile.length - 1; i >= 0; i--) {
            l1.removeElementAt(indexSelectedFile[i]);
        }
    }//GEN-LAST:event_removeFilePanelMouseClicked

    private void settingPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingPanelMouseClicked
        ABout about = new ABout();
        about.setVisible(true);
    }//GEN-LAST:event_settingPanelMouseClicked
    void setsavePath() {
        JFileChooser saveLocation = new JFileChooser();
        saveLocation.setDialogTitle("Select output file location");
        int result = saveLocation.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File fileToSave = saveLocation.getSelectedFile();
            lOutputPath.setText("<html><body><a href=''>" + fileToSave.toString() + "</a></body</html>");
        }
    }
    private void exitPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPanelMouseClicked
        System.exit(1);
    }//GEN-LAST:event_exitPanelMouseClicked

    private void bCombineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCombineActionPerformed

        try {
            CombinePDF c = new CombinePDF();
            c.start();
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_bCombineActionPerformed
    /*
     background thread to combine pdf
     */

    private class CombinePDF extends Thread {

        public void run() {

            if (l1.getSize() != 0) {

                String result = lOutputPath.getText().substring(23, lOutputPath.getText().length() - 18);
                if (!result.endsWith(".pdf")) {
                    result = result + ".pdf";

                }
                try {
                    File file = new File(result);

                    File parent = new File(file.getParent());
                    if (parent.exists()) {
                        String[] files = new String[l1.getSize()];
                        for (int i = 0; i < l1.getSize(); i++) {
                            files[i] = l1.getElementAt(i);
                        }
                        mergeFiles(files, result, true);
                    } else {
                        JOptionPane.showMessageDialog(null, "Please change Output Path");
                    }
                    l1.clear();

                } catch (IOException ex) {
                    Logger.getLogger(PDFCombine.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex);
                } catch (DocumentException ex) {
                    Logger.getLogger(PDFCombine.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        }

        public void mergeFiles(String[] files, String result, boolean smart) throws IOException, DocumentException {
            Document document = new Document();
            PdfCopy copy;

            if (smart) {
                copy = new PdfSmartCopy(document, new FileOutputStream(result));
            } else {
                copy = new PdfCopy(document, new FileOutputStream(result));
            }
            document.open();
            PdfReader[] reader = new PdfReader[files.length];
            float progress = 0.00f;
            float perFileProgress = 100.00f / files.length;
            System.out.print(files.length);
            for (int i = 0; i < files.length; i++) {
                reader[i] = new PdfReader(files[i]);
                copy.addDocument(reader[i]);
                copy.freeReader(reader[i]);
                reader[i].close();
                progress = progress + perFileProgress;
                progressBar.setValue((int) Math.ceil(progress));
                progressBar.setStringPainted(true);

            }
            document.close();
        }
    }
    private void addFilePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addFilePanelMousePressed
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/add-pressed.png")));
    }//GEN-LAST:event_addFilePanelMousePressed

    private void addFilePanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addFilePanelMouseReleased
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/add-hover.png")));
    }//GEN-LAST:event_addFilePanelMouseReleased

    private void addFolderPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addFolderPanelMousePressed
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/folder-pressed.png")));
    }//GEN-LAST:event_addFolderPanelMousePressed

    private void addFolderPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addFolderPanelMouseReleased
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/folder-hover.png")));
    }//GEN-LAST:event_addFolderPanelMouseReleased

    private void removeFilePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeFilePanelMouseEntered
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/delete-hover.png")));
    }//GEN-LAST:event_removeFilePanelMouseEntered

    private void removeFilePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeFilePanelMouseExited
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/delete.png")));
    }//GEN-LAST:event_removeFilePanelMouseExited

    private void removeFilePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeFilePanelMousePressed
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/delete-pressed.png")));
    }//GEN-LAST:event_removeFilePanelMousePressed

    private void removeFilePanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeFilePanelMouseReleased
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/delete-hover.png")));
    }//GEN-LAST:event_removeFilePanelMouseReleased

    private void settingPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingPanelMouseEntered
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/about-hover.png")));
    }//GEN-LAST:event_settingPanelMouseEntered

    private void settingPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingPanelMouseExited
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/about.png")));
    }//GEN-LAST:event_settingPanelMouseExited

    private void settingPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingPanelMousePressed
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/about-pressed.png")));    }//GEN-LAST:event_settingPanelMousePressed

    private void settingPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingPanelMouseReleased
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/about-hover.png")));

    }//GEN-LAST:event_settingPanelMouseReleased

    private void exitPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPanelMouseEntered
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/exit-hover.png")));
    }//GEN-LAST:event_exitPanelMouseEntered

    private void exitPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPanelMouseExited
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/exit.png")));
    }//GEN-LAST:event_exitPanelMouseExited

    private void exitPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPanelMousePressed
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/exit-pressed.png")));
    }//GEN-LAST:event_exitPanelMousePressed

    private void exitPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPanelMouseReleased
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/exit-hover.png")));
    }//GEN-LAST:event_exitPanelMouseReleased

    private void lOutputPathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lOutputPathMouseClicked
        setsavePath();
    }//GEN-LAST:event_lOutputPathMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lOutputPath.setText("<html><body><a href=''>C:\\PDFCombine\\combined.pdf</a></body></html>");

        File f = new File("C:\\PDFCombine");
        f.mkdir();

    }//GEN-LAST:event_formWindowOpened

    private void bUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpActionPerformed
        if (l1.size() != 0) {
            try {
                int selected = itemList.getSelectedIndex();
                String selctedItem = l1.getElementAt(selected);
                String temp = l1.getElementAt(selected - 1);

                l1.setElementAt(temp, selected);
                l1.setElementAt(selctedItem, selected - 1);
                Robot r = new Robot();
                r.keyPress(KeyEvent.VK_UP);
            } catch (AWTException ex) {
                Logger.getLogger(PDFCombine.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bUpActionPerformed

    private void bDown1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDown1ActionPerformed
        if (l1.getSize() != 0) {
            int size = l1.getSize();
            String[] list = new String[size];
            for (int i = 0; i < l1.getSize(); i++) {
                list[i] = l1.getElementAt(i);
            }
            l1.removeAllElements();
            for (int i = size - 1; i > -1; i--) {
                l1.addElement(list[i]);
            }
        }
    }//GEN-LAST:event_bDown1ActionPerformed

    private void bDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDownActionPerformed
        if (l1.size() != 0) {
            try {
                int selected = itemList.getSelectedIndex();
                String selctedItem = l1.getElementAt(selected);
                String temp = l1.getElementAt(selected + 1);

                l1.setElementAt(temp, selected);
                l1.setElementAt(selctedItem, selected + 1);
                Robot r = new Robot();
                r.keyPress(KeyEvent.VK_UP);
            } catch (AWTException ex) {
                Logger.getLogger(PDFCombine.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bDownActionPerformed

    void addFilePathtoList(File[] file, String source) {
        int count = 0;
        for (File file1 : file) {
            if (file1.isFile() && file1.toString().endsWith(".pdf")) {
                l1.addElement(file1 + "");
                count++;
            }
        }
        if (count == 0) {
            if (source.equalsIgnoreCase("folder")) {
                JOptionPane.showMessageDialog(null, "Selected folder diesn't contain any PDF files", "No PDF File Selected", WIDTH);
            }

            if (source.equalsIgnoreCase("file")) {
                JOptionPane.showMessageDialog(null, "No PDF file selected", "No PDF File Selected", WIDTH);
            }
        }
        itemList.setModel(l1);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PDFCombine.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PDFCombine.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PDFCombine.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PDFCombine.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PDFCombine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addFilePanel;
    private javax.swing.JPanel addFolderPanel;
    private javax.swing.JButton bCombine;
    private javax.swing.JButton bDown;
    private javax.swing.JButton bDown1;
    private javax.swing.JButton bUp;
    private javax.swing.JPanel exitPanel;
    private javax.swing.JList itemList;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lOutputPath;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JPanel removeFilePanel;
    private javax.swing.JPanel settingPanel;
    // End of variables declaration//GEN-END:variables
}
